name: Rust

on:
  push:
    branches:
      - main
  pull_request:

jobs:   
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update toolchain
        run: |
          rustup update
          rustup component add rustfmt
          rustup component add clippy
      - name: Rust lint
        run: |
          cargo fmt --check
          cargo clippy -- -D warnings
          
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run:
          cargo test
          
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update toolchain
        run: |
          rustup update
          cargo install cargo-tarpaulin
      - name: Code coverage
        run:
          cargo tarpaulin --ignore-tests
