name: Rust

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add rustfmt
          rustup component add clippy
          cargo install cargo-tarpaulin
          
      - name: Rust lint
        run: |
          cargo fmt --check
          cargo clippy -- -D warnings
          
      - name: Run tests
        run:
          cargo test
          
      - name: Code coverage
        run:
          cargo tarpaulin --ignore-tests
