name: Rust

on:
  push:
    branches:
      - main
  pull_request:

jobs:   
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update toolchain
        run: |
          rustup update
          rustup component add rustfmt
      - name: Format
        run: |
          cargo fmt --check
          
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update toolchain
        run: |
          rustup update
          rustup component add clippy
      - name: Clippy
        run: |
          cargo clippy -- -D warnings
          
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update toolchain
        run: |
          rustup update
      - name: Run tests
        run:
          cargo test
