name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add rustfmt
          rustup component add clippy
          cargo install cargo-tarpaulin
          
      - name: Format
        run:
          cargo fmt --check
          
      - name: Cargo clippy
        run:
          cargo clippy -- -D warnings
          
      - name: Rust lint
        run:
          cargo test
          
      - name: Code coverage
        run:
          cargo tarpaulin --ignore-tests
