name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:   
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update toolchain
        run: |
          rustup update
          rustup component add rustfmt
      - name: Format
        run: |
          cargo fmt --check
          
  lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5321:5432
    env:
      SQLX_VERSION: 0.6.2
      SQLX_FEATURES: "rustls,postgres"
    steps:
      - uses: actions/checkout@v3
      - name: Update toolchain
        run: |
          rustup update
          rustup component add clippy
          
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache sqlx-cli
        uses: actions/cache@v3
        id: cache-sqlx
        with:
          path: |
            ~/.cargo/bin/sqlx
          key: ${{ runner.os }}-sqlx-${{ env.SQLX_VERSION }}

      - name: Install sqlx-cli
        if: steps.cache-sqlx.outputs.cache-hit == false
        run:
          cargo install sqlx-cli --force --locked --version ${{ env.SQLX_VERSION }} --no-default-features --features ${{ env.SQLX_FEATURES }}

      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          SKIP_DOCKER=true ./scripts/init_db.sh
          
      - name: Clippy
        run: |
          cargo clippy --all-targets -- -D warnings
          
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5321:5432
    env:
      SQLX_VERSION: 0.6.2
      SQLX_FEATURES: "rustls,postgres"
    steps:
      - uses: actions/checkout@v3
      - name: Update toolchain
        run: |
          rustup update
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache sqlx-cli
        uses: actions/cache@v3
        id: cache-sqlx
        with:
          path: |
            ~/.cargo/bin/sqlx
            ~/.cargo/bin/cargo-sqlx
          key: ${{ runner.os }}-sqlx-${{ env.SQLX_VERSION }}

      - name: Install sqlx-cli
        if: steps.cache-sqlx.outputs.cache-hit == false
        run:
          cargo install sqlx-cli --force --locked --version ${{ env.SQLX_VERSION }} --no-default-features --features ${{ env.SQLX_FEATURES }}

      - name: Migrate database
        run: |
          sudo apt install libpq-dev -y
          SKIP_DOCKER=true ./scripts/init_db.sh
          
      - name: Check sqlx-data.json is up-to-date
        run:
          cargo sqlx prepare --check -- --bin zero2prod

      - name: Run tests
        run:
          cargo test
          
